---
title: Carina Mirzaeva
timezone: UTC
collections:
  categories:
    title: Categories
    output: true
    permalink: "/personal/:title"
  personal:
    title: Personal
    output: false
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    video_url: 
    description: 
- scope:
    path: ''
    type: personal
  values:
    image: 
    link: 
    published: 
description: Animation
section_title: Œuvres en vedette
section_subtitle: 
email: carrylionart@gmail.com
baseurl: 
url: https://carrylion.fr
social:
- url: https://instagram.com/carrylionart
  text: instagram
- url: https://vimeo.com/carrylion
  text: vimeo
- url: https://carrylion.tumblr.com/
  text: tumblr
- url: https://www.linkedin.com/in/carrylion/
  text: linkedin
demoreel_url: https://vimeo.com/435476536
footer_text: "© 2020 Carina Mirzaeva"
admin_name: Carrylion
google_analytics: UA-9999999-99
enable_contact: true
enable_nav: true
nav_item:
- url: "/collaborations"
  text: Collaborations
- url: "/personal"
  text: Personnelle
  popup_collection: categories
- url: "/about"
  text: Sur
exclude:
- ".sass-cache/"
- ".jekyll-cache/"
- gemfiles/
- Gemfile
- Gemfile.lock
- ".git"
- ".idea"
