
title: "Carina Mirzaeva"
description: "Animation"
email: 'carrylion@gmail.com'
baseurl: ""
url: "https://carrylion.fr"

instagram: "https://www.instagram.com/carrylionart/"
linkedin: "https://www.linkedin.com/in/carrylion/"
vimeo: "https://vimeo.com/carrylion"
tumblr: "https://carrylion.tumblr.com/"


footer_text: '© 2020 Carina Mirzaeva'
admin_name: 'Carrylion'
google_analytics: "UA-9999999-99"
enable_contact: false

enable_nav: true
nav_item:
  - { url: '/', text: 'Home' }
  - { url: '/about', text: 'About' }

exclude:
- ".sass-cache/"
- ".jekyll-cache/"
- gemfiles/
- Gemfile
- Gemfile.lock
- ".git"
- ".idea"
